### PR TITLE
remove xrange

### PR DESCRIPTION
**Pull request by StuartLittlefair**
Hi Tom,

trm.roche.__init__ uses ```xrange``` which dies under python3. Here's a small PR to fix this

### CODE REVIEW

**Review by trmrsh — COMMENTED** [review]
Hi Stu, seem to be quite a few changes here; probably OK but what are they all about?

tom

**Comment by trmrsh** [comment]
actually, sorry I see the xrange thing; don't quite understand how I can have got away for so long without running into it.

**Comment by StuartLittlefair** [comment]
I’d forgotten this branch had an open PR. The xrange thing is for py3, but the latest commit was fixing some issues we occasionally ran into with `stradv` not working. 

It looks like a lot of changes as my editor has automatically fixed up whitespace. I hate it when it does that.

**Comment by StuartLittlefair** [comment]
In the 2nd commit the only change is moving the step size in stradv from 1e-2 to 1e-3

**Pull request merged**
